[shell]
program = "C:/Windows/System32/wsl.exe"

[font]
normal.family = "Hackgen Console"

[keyboard]
bindings = [
  { key = "PageUp", mods = "None", action = "ScrollLineUp" },
  { key = "PageDown", mods = "None", action = "ScrollLineDown" }
]
