[shell]
program = "C:/Windows/System32/wsl.exe"

[font]
normal.family = "HackGen Console NF"

[keyboard]
bindings = [
  { key = "PageUp", mods = "None", action = "ScrollLineUp" },
  { key = "PageDown", mods = "None", action = "ScrollLineDown" },

  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" }
]
